apiVersion: v1
kind: ConfigMap
metadata:
  name: api-mcs-vip-conf
  namespace: ocp-vip
data:
  keepalived.conf: |
    global_defs {
      router_id ocp-vip
    }
    vrrp_script probe_script {
      script "/bin/sh -c /probe.sh"
      interval 10
      weight 5
      rise 1
    }
    vrrp_instance VIP {
      virtual_ingress_id 50
      advert_int 1
      priority 100
      state MASTER
      interface eth0
      virtual_ipaddress {
        198.18.100.100 dev eth0
      }
      track_script {
        probe_script
      }
    }
  probe.sh: |
    #!/bin/bash

    TARGET_IP="localhost"

    API_HEALTHZ=`curl -o /dev/null -s -w "%{http_code}" -k https://${TARGET_IP}:6443/healthz`
    MCS_HEALTHZ=`curl -o /dev/null -s -w "%{http_code}" -k https://${TARGET_IP}:22623/healthz`

    if [ "${API_HEALTHZ}" -eq "200" ] && [ "${MCS_HEALTHZ}" -eq "200" ]; then
        exit 0
    else
        exit 1
    fi