apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ocp-vip-role
rules:
- apiGroups:
  - ""
  resources:
#  - namespaces
  - services
  - endpoints
  - nodes
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-vip-role-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: ocp-vip-role
subjects:
- kind: ServiceAccount
  namespace: ocp-vip
  name: ocp-vip-sa
---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-vip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-vip-sa
  namespace: ocp-vip