apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-vip
  labels:
    app: ingress-vip
    vip: ingress-vip
  namespace: ocp-vip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingress-vip
      vip: ingress-vip
  template:
    metadata:
      labels:
        app: ingress-vip
        vip: ingress-vip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: vip
                operator: In
                values:
                - ingress-vip
            topologyKey: kubernetes.io/hostname
      containers:
      - name: ocp-vip
        image: quay.io/wcaban/ocp-vip
        imagePullPolicy: Always
        env: 
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command: [ "/entrypoint.sh" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: vip-configuration
          mountPath: /vip
      volumes:
        - name: vip-configuration
          configMap:
            name: ingress-vip-conf
      restartPolicy: Always
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
      env: 
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      hostNetwork: true
      serviceAccountName: ocp-vip-sa
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300