apiVersion: v1
kind: Pod
metadata:
  generateName: ingress-vip-
  annotations:
    openshift.io/scc: hostnetwork
  namespace: ocp-vip
  labels:
    ocp-vip: ingress-vip
spec:
  affinity:
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchFields:
    #       - key: node-role.kubernetes.io/master
    #         operator: Exists
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: ocp-vip
            operator: In
            values:
            - ingress-vip
        topologyKey: kubernetes.io/hostname
  containers:
    - name: ocp-vip
      image: quay.io/wcaban/ocp-vip
      command: [ "keepalived", "-P", "-D", "-l", "-n", "-f /keepalived.conf" ]
      volumeMounts:
      - name: vip-configuration
        mountPath: /
  volumes:
    - name: vip-configuration
      configMap:
        name: api-mcs-vip-conf
  restartPolicy: Always
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
  securityContext:
   privileged: true
  hostNetwork: true
  # serviceAccountName: ocp-vip-sa
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  # tolerations:
  # - effect: NoSchedule
  #   key: node.kubernetes.io/memory-pressure
  #   operator: Exists
  # - effect: NoExecute
  #   key: node.kubernetes.io/unreachable
  #   operator: Exists
  #   tolerationSeconds: 300
  # - effect: NoExecute
  #   key: node.kubernetes.io/not-ready
  #   operator: Exists
  #   tolerationSeconds: 300