apiVersion: v1
kind: Pod
metadata:
  generateName: ingress-vip-
spec:
  containers:
    - name: ocp-vip
      image: quay.io/wcaban/ocp-vip
      command: [ "keepalived", "-P", "-D", "-l", "-n", "-f /keepalived.conf" ]
      volumeMounts:
      - name: vip-configuration
        mountPath: /
  volumes:
    - name: vip-configuration
      configMap:
        name: api-mcs-vip-conf
  restartPolicy: Always