apiVersion: v1
kind: Pod
metadata:
  generateName: ingress-vip-
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: node-role.kubernetes.io/master
            operator: In
            values:
            - ""
  containers:
    - name: ocp-vip
      image: quay.io/wcaban/ocp-vip
      command: [ "keepalived", "-P", "-D", "-l", "-n", "-f /keepalived.conf" ]
      volumeMounts:
      - name: vip-configuration
        mountPath: /
  volumes:
    - name: vip-configuration
      configMap:
        name: api-mcs-vip-conf
  restartPolicy: Always
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
#  securityContext:
#    privileged: true
  hostNetwork: true
  serviceAccountName: ocp-vip-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - operator: Exists