apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mcs-vip
  labels:
    app: api-mcs-vip
    vip: api-mcs-vip
  namespace: ocp-vip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-mcs-vip
      vip: api-mcs-vip
  template:
    metadata:
      labels:
        app: api-mcs-vip
        vip: api-mcs-vip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: vip
                operator: In
                values:
                - api-mcs-vip
            topologyKey: kubernetes.io/hostname
      containers:
      - name: ocp-vip
        image: quay.io/wcaban/ocp-vip
        imagePullPolicy: Always
        command: [ "/entrypont.sh" ]
        volumeMounts:
        - name: vip-configuration
          mountPath: /vip
      volumes:
        - name: vip-configuration
          configMap:
            name: api-mcs-vip-conf
      restartPolicy: Always
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
      hostNetwork: true
      serviceAccountName: ocp-vip-sa
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300